export const currency_seeds = [
  { name: 'Argentine Peso', value: 'ars' },
  { name: 'Australian Dollar', value: 'aud' },
  { name: 'Brazilian Real', value: 'brl' },
  { name: 'British Pound', value: 'gbp' },
  { name: 'Canadian Dollar', value: 'cad' },
  { name: 'Chinese Yuan', value: 'cny' },
  { name: 'Egyptian Pound', value: 'egp' },
  { name: 'Euro', value: 'eur' },
  { name: 'Hong Kong Dollar', value: 'hkd' },
  { name: 'Indian Rupee', value: 'inr' },
  { name: 'Indonesian Rupiah', value: 'idr' },
  { name: 'Japanese Yen', value: 'jpy' },
  { name: 'Malaysian Ringgit', value: 'myr' },
  { name: 'Mexican Peso', value: 'mxn' },
  { name: 'New Zealand Dollar', value: 'nzd' },
  { name: 'Norwegian Krone', value: 'nok' },
  { name: 'Pakistani Rupee', value: 'pkr' },
  { name: 'Philippine Peso', value: 'php' },
  { name: 'Polish Zloty', value: 'pln' },
  { name: 'Russian Ruble', value: 'rub' },
  { name: 'Singapore Dollar', value: 'sgd' },
  { name: 'South African Rand', value: 'zar' },
  { name: 'South Korean Won', value: 'krw' },
  { name: 'Swedish Krona', value: 'sek' },
  { name: 'Swiss Franc', value: 'chf' },
  { name: 'Thai Baht', value: 'thb' },
  { name: 'Turkish Lira', value: 'try' },
  { name: 'United Arab Emirates Dirham', value: 'aed' },
  { name: 'US Dollar', value: 'usd' },
  { name: 'Vietnamese Dong', value: 'vnd' },
];
